---
- name: Install Node Exporter
  hosts: node_exporter
  gather_facts: yes
  become: yes
  roles:
    - node_exporter
  
- name: Install Prometheus
  hosts: promethues
  gather_facts: yes
  become: yes
  roles:
    - prometheus

- name: Install Grafana
  hosts: grafana
  gather_facts: yes
  become: yes
  roles:
    - grafana