---
all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
    ansible_ssh_private_key_file: /root/.ssh/id_rsa

    airgapped_installation_mode: true

promethues:
  vars:
    prometheus_archive_file_source: /home/administrator/Downloads/prometheus-2.45.4.linux-amd64.tar.gz

    prometheus_version: 2.45.4
    
    prometheus_custom_config:
      scrape_interval: 10s

    prometheus_jobs:
      - name: kafka_broker
        targets:
          - 1.2.3.4:8080
          - 1.2.3.5:8080
          - 1.2.3.6:8080 
        labels:
          env: dev
           
      - name: zookeeper
        targets: 
          - 1.2.4.1:8079
          - 1.2.4.2:8079
          - 1.2.4.3:8079
        labels:
          env: dev

  hosts:
    c7d96d4d6c654c2eb9e2b9c7cc2da8d22d.mylabserver.com:

grafana:
  vars:
    grafana_archive_file_source: /home/administrator/Downloads/grafana-10.4.2.linux-amd64.tar.gz
    grafana_version: 10.4.2
    grafana_user: grafana
    grafana_group: grafana
    grafana_admin_username: grafana
    grafana_admin_password: password

    grafana_ssl_enabled: true

    grafana_install_dir: /opt/grafana
    grafana_log_dir: /var/log/grafana
    grafana_plugins_dir: /var/lib/grafana/plugins
    # Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
    grafana_data_dir: /var/lib/grafana

    grafana_custom_configs:

    grafana_custom_dashboards:
      - /home/administrator/projects/jmx-playbook/roles/grafana/files/custom_dashboards/example1.json
      - /home/administrator/projects/jmx-playbook/roles/grafana/files/custom_dashboards/example2.json

  hosts:
    c7d96d4d6c654c2eb9e2b9c7cc2da8d22d.mylabserver.com:

node_exporter:
  vars:
    node_exporter_version: 1.8.0
    node_exporter_package: /home/administrator/Downloads/node_exporter-1.8.0.linux-amd64.tar.gz
  
    node_exporter_install_dir: "/usr/local/bin"
    node_exporter_listen_address: ":9100"
    node_exporter_user: "node_exporter"
    node_exporter_group: "node_exporter"
    node_exporter_telemetry_path: "/metrics"
    node_exporter_log_level: "info"
  
  hosts:
    c7d96d4d6c654c2eb9e2b9c7cc2da8d22d.mylabserver.com: